<!doctype html>
<html lang="§">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Сторінка не знайдена | Інтернет-магазин "Весна"</title>
	<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body>
	<main class="flex flex-col items-center justify-center h-dvh w-full gap-5">
		<h1 class="scroll-m-20 text-4xl font-extrabold tracking-tight lg:text-5xl">404</h1>
		<h3 class="scroll-m-20 text-2xl font-semibold tracking-tight">Сторінка не знайдена</h3>
		<div class="inline-flex gap-4">
			<a href="/" class="flex bg-indigo-500 text-white items-center justify-center h-9 px-3 min-w-[128px] rounded-lg text-sm hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">На головну</a>
		</div>
	</main>
</body>
</html>