<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Головна | Інтернет-магазин "Весна"</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="flex flex-col w-full h-dvh mt-auto">
  <?php include './templates/navbar.phtml'; ?>
  <main class="flex flex-col size-full items-center justify-center bg-slate-50 gap-4">
    <?php if( isset( $_SESSION['username'] )) : ?>
      <h1 class="scroll-m-20 text-2xl font-semibold tracking-tight">Привіт <?= $_SESSION['username'] ?>!</h1>
    <?php else : ?>
      <?php include './templates/auth-required.phtml'; ?>
    <?php endif; ?>
  </main>
  <?php include './templates/footer.phtml'; ?>
</body>
</html>
