<?php
require_once 'services/UsersService.php';
require_once 'services/UploadService.php';
include 'stores/profile.php';

if ($_SERVER["REQUEST_METHOD"] === "POST" && isset($_POST['first_name'])) {
	try {
		UsersService::updateProfile($_POST);
	} catch (Exception $e) {
		$error = $e->getMessage();
	}
}

if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_FILES['avatar'])) {
	try {
		UploadService::uploadImage();
	} catch (Exception $e) {
		$error = $e->getMessage();
	}
}
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Профіль | Інтернет-магазин "Весна"</title>
	<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="flex flex-col w-full h-dvh mt-auto">
<?php include './templates/navbar.phtml'; ?>
<main class="flex flex-col size-full items-center justify-center bg-slate-50 gap-4">
	<div class="max-w-5xl mx-auto bg-white p-8 rounded-lg shadow-md">
		<div class="grid grid-cols-1 md:grid-cols-3 gap-8">

			<div class="flex flex-col items-center space-y-4">
        <img src="<?= $profile['avatar'] ?? 'assets/fallback-image.jpg' ?>" alt="avatar" class="w-48 h-48 rounded-2xl">
        <form id="upload_form" method="post" enctype="multipart/form-data">
          <input id="upload" type="file" name="avatar" accept="image/*" required hidden />
          <label for="upload" class="flex bg-white items-center items-center leading-none text-black h-9 px-3 min-w-[128px] rounded-lg text-sm border border-slate-300 hover:bg-slate-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            Завантажити
          </label>
        </form>
			</div>

			<form class="md:col-span-2 space-y-6" method="post">
				<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
					<div>
						<label for="first_name" class="block text-sm font-semibold mb-1">Імʼя</label>
						<input
							id="first_name"
							name="first_name"
							type="text"
							placeholder="Введіть імʼя"
							class="bg-gray-50 border border-gray-300 text-black text-sm rounded-lg focus:ring-blue-500 focus:border-indigo-500 focus:ring focus:ring-indigo-500 block w-full p-2.5"
							value="<?= $profile['first_name'] ?? '' ?>"
							autofocus
							required
						/>
					</div>
					<div>
						<label for="last_name" class="block text-sm font-semibold mb-1">Прізвище</label>
						<input
							id="last_name"
							name="last_name"
							type="text"
							placeholder="Введіть прізвище"
							class="bg-gray-50 border border-gray-300 text-black text-sm rounded-lg focus:ring-blue-500 focus:border-indigo-500 focus:ring focus:ring-indigo-500 block w-full p-2.5"
							value="<?= $profile['last_name'] ?? '' ?>"
							required
						/>
					</div>
					<div>
						<label class="block text-sm font-semibold mb-1">Дата народження</label>
						<input
							id="date_of_birth"
							name="date_of_birth"
							type="date"
							placeholder="Введіть імʼя"
							class="bg-gray-50 border border-gray-300 text-black text-sm rounded-lg focus:ring-blue-500 focus:border-indigo-500 focus:ring focus:ring-indigo-500 block w-full p-2.5"
							value="<?= $profile['date_of_birth'] ?? '' ?>"
							required
						/>
					</div>
				</div>

				<div>
					<label for="description" class="block text-sm font-semibold mb-1">Опис</label>
					<input
						id="description"
						name="description"
						class="bg-gray-50 border border-gray-300 text-black text-sm rounded-lg focus:ring-blue-500 focus:border-indigo-500 focus:ring focus:ring-indigo-500 block w-full p-2.5"
						placeholder="Напишіть щось про себе..."
						value="<?= $profile['description'] ?? '' ?>"
					>
				</div>

				<?php if (!empty($error)) : ?>
					<p class="text-red-500"><?= htmlspecialchars($error) ?></p>
				<?php endif ?>
				<div class="flex justify-end">
					<button class="bg-indigo-500 text-white h-9 px-3 min-w-[128px] rounded-lg text-sm hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 ml-auto">
						Зберегти
					</button>
				</div>
			</form>
		</div>
	</div>
</main>
<?php include './templates/footer.phtml'; ?>
<script>
  document.getElementById('upload').addEventListener('change', function () {
    if (this.files.length > 0) {
      document.getElementById('upload_form').submit();
    }
  });
</script>
</body>
</html>
